-- AlterTable
ALTER TABLE "siniestros" ADD COLUMN     "cambio_estatus_final_total_vendido" BOOLEAN,
ADD COLUMN     "cambio_estatus_p_total" TEXT,
ADD COLUMN     "carta_levantamiento_prenda_banco" TEXT,
ADD COLUMN     "doc_certificado_gravamen" TEXT,
ADD COLUMN     "doc_comprobante_pago_matricula" TEXT,
ADD COLUMN     "doc_copia_ci_pv_ruc_rl" TEXT,
ADD COLUMN     "doc_copia_factura_venta" TEXT,
ADD COLUMN     "doc_cuv_final" TEXT,
ADD COLUMN     "doc_original_copia_llave" TEXT,
ADD COLUMN     "doc_original_matricula" TEXT,
ADD COLUMN     "doc_vehiculo_sin_multas" TEXT,
ADD COLUMN     "entrega_cheque_financiero" TEXT,
ADD COLUMN     "entrega_documentos_broker" TEXT,
ADD COLUMN     "entrega_estado_financiero_banco_prenda" BOOLEAN,
ADD COLUMN     "fecha_declaratoria_perdida_total" TIMESTAMP(3),
ADD COLUMN     "fecha_pago_perdida_total" TIMESTAMP(3),
ADD COLUMN     "fecha_retiro_sustituto_pt" TIMESTAMP(3),
ADD COLUMN     "fecha_solicitud_cambio_estatus_kimerasoft" TIMESTAMP(3),
ADD COLUMN     "fecha_solicitud_liberacion_prenda" TIMESTAMP(3),
ADD COLUMN     "firma_contrato_compra_venta_notaria" TEXT,
ADD COLUMN     "gestion_renovacion_vehiculo" TEXT,
ADD COLUMN     "motivo_perdida_total" TEXT,
ADD COLUMN     "nombre_banco_prenda" TEXT,
ADD COLUMN     "notificacion_retiro_sustituto_pt" TIMESTAMP(3),
ADD COLUMN     "porcentaje_avance_checklist" DOUBLE PRECISION,
ADD COLUMN     "solicitud_cambio_estatus_kimerasoft" BOOLEAN,
ADD COLUMN     "tramite_liberacion_prenda" TEXT,
ADD COLUMN     "valor_indemnizado_pt1" DOUBLE PRECISION,
ADD COLUMN     "valor_pendiente_indemnizacion_pt2" DOUBLE PRECISION;
