-- AlterTable
ALTER TABLE "siniestros" ADD COLUMN     "abogado_asignado" TEXT,
ADD COLUMN     "causal_detencion" TEXT,
ADD COLUMN     "cobertura_tasa_spatt_ocupante_lesionado" DOUBLE PRECISION,
ADD COLUMN     "cobertura_todo_riesgo_fallecido" DOUBLE PRECISION,
ADD COLUMN     "confirmacion_acompanamiento_abogado_penal" TIMESTAMP(3),
ADD COLUMN     "deducible_robo_componentes_electronicos" DOUBLE PRECISION,
ADD COLUMN     "estado_vehiculo_recuperado" TEXT,
ADD COLUMN     "fecha_asignacion_fiscalia" TIMESTAMP(3),
ADD COLUMN     "fecha_denuncia_robo" TIMESTAMP(3),
ADD COLUMN     "fecha_envio_parte_broker" TIMESTAMP(3),
ADD COLUMN     "fecha_liberacion_vehiculo" TIMESTAMP(3),
ADD COLUMN     "fecha_orden_liberacion" TIMESTAMP(3),
ADD COLUMN     "fecha_pago_facturas_tasa_spatt" TIMESTAMP(3),
ADD COLUMN     "fecha_recuperacion" TIMESTAMP(3),
ADD COLUMN     "fecha_seguimiento_parte_policial" TIMESTAMP(3),
ADD COLUMN     "gastos_ambulancia" DOUBLE PRECISION,
ADD COLUMN     "gastos_funerarios_fallecido" DOUBLE PRECISION,
ADD COLUMN     "hay_personas_fallecidas" BOOLEAN,
ADD COLUMN     "hay_personas_lesionadas" BOOLEAN,
ADD COLUMN     "historia_clinica_solicitada" BOOLEAN,
ADD COLUMN     "limite_seguro_todo_riesgo_si_supera_spatt" DOUBLE PRECISION,
ADD COLUMN     "numero_denuncia" TEXT,
ADD COLUMN     "numero_fallecidos" INTEGER,
ADD COLUMN     "numero_ocupantes_lesionados" INTEGER,
ADD COLUMN     "requiere_acompanamiento_abogado_penal" BOOLEAN,
ADD COLUMN     "seguimiento_indemnizacion_tercero" TEXT,
ADD COLUMN     "seguimiento_indemnizacion_usuario" TEXT,
ADD COLUMN     "total_tiempo_siniestro" DOUBLE PRECISION,
ADD COLUMN     "valor_cancelar_grua" DOUBLE PRECISION,
ADD COLUMN     "valor_cancelar_parqueadero" DOUBLE PRECISION,
ADD COLUMN     "vehiculo_detenido_tras_recuperacion" BOOLEAN,
ADD COLUMN     "vehiculo_recuperado" BOOLEAN;
